PADDLE_SIZE = 5
BALL_SIZE = 10
BRICK_HEIGHT = 20
BRICK_WIDTH = 40
BRICK_GAP = 5
BRICKS_PER_ROW = 14
SCREEN_WIDTH = round((BRICK_WIDTH + BRICK_GAP) *
                     BRICKS_PER_ROW + BRICK_GAP, -1)
print(SCREEN_WIDTH)
SCREEN_HEIGHT = SCREEN_WIDTH * (1 + 5 ** 0.5) / 2 // 10 * 10
SCREEN_TOP = SCREEN_HEIGHT // 2
SCREEN_BOTTOM = SCREEN_HEIGHT // -2
SCREEN_LEFT = SCREEN_WIDTH // -2
SCREEN_RIGHT = SCREEN_WIDTH // 2
PADDLE_Y = SCREEN_BOTTOM + 40
PADDLE_WIDTH = PADDLE_SIZE * 20
PADDLE_HEIGHT = 10
GRAVEYARD = (1000, 1000)
