# BRICKS
BRICK_GAP = 4
BRICK_WIDTH = BRICK_GAP * 8
BRICK_HEIGHT = BRICK_GAP * 2
BRICKS_PER_ROW = 14
NUMBER_OF_ROWS = 8
BRICK_COLORS = ['red', 'orange', 'green', 'yellow']
# BALLS
BALL_SIZE = BRICK_GAP * 2
BALL_SPEED = .015
NUMBER_OF_BALLS = 3
SPEED_MULTIPLIER = .7
# WINDOW
SCREEN_WIDTH = int((BRICK_WIDTH + (BRICK_GAP * 2)) *
                   BRICKS_PER_ROW - (BRICK_GAP * 2))
SCREEN_HEIGHT = int(SCREEN_WIDTH * (1 + 5 ** 0.5) / 2 //
                    (BRICK_GAP * 2) * (BRICK_GAP * 2))
# PLAY AREA
SCREEN_TOP = SCREEN_HEIGHT // 2 - BRICK_HEIGHT * 20
SCREEN_BOTTOM = SCREEN_HEIGHT // -2
SCREEN_LEFT = SCREEN_WIDTH // -2
SCREEN_RIGHT = SCREEN_WIDTH // 2
# SCOREBOARD
TOP_GAP = BRICK_GAP * 12
SCOREBOARD_HEIGHT = SCREEN_HEIGHT - SCREEN_TOP
SCOREBOARD_TOP = SCREEN_HEIGHT // 2
FONT_NAME = 'Courier'
# PADDLE
PADDLE_WIDTH = BRICK_GAP * 25
PADDLE_HEIGHT = BALL_SIZE
PADDLE_Y = SCREEN_BOTTOM + BRICK_GAP * 20
PADDLE_COLOR = 'dodgerblue'
# OTHER
GRAVEYARD = (1000, 1000)
